import type { Metadata } from "next";

import { AppThemeProvider } from "./theme/themeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppThemeProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </AppThemeProvider>


  );
}